products = [
    {
      id: 1,
      collection: "Rittis",
      productName: "Rittis-1",
      isWished: false,
      price: 92.95,
      totalPrice: 0,
      stone: "sona diamond",
      carat: 15,
      cut: "cushion",
      img: "./../../assets/images/collections/rittis/Rittis-1.jpg",
      material: "yellow gold 18k",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    },
    {
      id: 2,
      collection: "Rittis",
      productName: "Rittis-2",
      isWished: false,
      price: 73.95,
      totalPrice: 0,
      stone: "sona diamond",
      carat: 15,
      cut: "princess",
      img: "./../../assets/images/collections/rittis/Rittis-2.jpg",
      material: "yellow gold 18k",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    },
    {
      id: 3,
      collection: "Rittis",
      productName: "Rittis-3",
      isWished: false,
      price: 51.95,
      totalPrice: 0,
      stone: "moissanite",
      carat: 15,
      cut: "princess",
      img: "./../../assets/images/collections/rittis/Rittis-3.jpg",
      material: "platinum 14k",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    },
    {
      id: 4,
      collection: "Biafin",
      productName: "Biafin-1",
      isWished: false,
      price: 23.95,
      totalPrice: 0,
      stone: "zircone",
      carat: 0,
      cut: "flower",
      img: "./../../assets/images/collections/biafin/Biafin-1.jpg",
      material: "dipped rose gold",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    },
    {
      id: 5,
      collection: "Biafin",
      productName: "Biafin-2",
      isWished: false,
      price: 16.95,
      totalPrice: 0,
      stone: "zircone",
      carat: 0,
      cut: "flower",
      img: "./../../assets/images/collections/biafin/Biafin-2.jpg",
      material: "dipped black gold",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    },
    {
      id: 6,
      collection: "Biafin",
      productName: "Biafin-3",
      isWished: false,
      price: 244.95,
      totalPrice: 0,
      stone: "real ruby",
      carat: 4,
      cut: "flower",
      img: "./../../assets/images/collections/biafin/Biafin-3.jpg",
      material: "rose gold 18k",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    },
    {
      id: 7,
      collection: "Sultavia",
      productName: "Sultavia-1",
      isWished: false,
      price: 87.95,
      totalPrice: 0,
      stone: "cr sapphire",
      carat: 7,
      cut: "oval",
      img: "./../../assets/images/collections/sultavia/Sultavia-1.jpg",
      material: "silver 15k",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    },
    {
      id: 8,
      collection: "Sultavia",
      productName: "Sultavia-2",
      isWished: false,
      price: 22.95,
      totalPrice: 0,
      stone: "rainbow zircone",
      carat: 5,
      cut: "pearl",
      img: "./../../assets/images/collections/sultavia/Sultavia-2.jpg",
      material: "platinum 15k",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    },
    {
      id: 9,
      collection: "Sultavia",
      productName: "Sultavia-3",
      isWished: false,
      price: 381.95,
      totalPrice: 0,
      stone: "real ruby",
      carat: 9,
      cut: "oval",
      img: "./../../assets/images/collections/sultavia/Sultavia-3.jpg",
      material: "yellow gold 18k",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    },
    {
      id: 10,
      collection: "Prestias",
      productName: "Prestias-1",
      isWished: false,
      price: 95.95,
      totalPrice: 0,
      stone: "sona diamond",
      carat: 8,
      cut: "heart",
      img: "./../../assets/images/collections/prestias/Prestias-1.jpg",
      material: "yellow gold 18k",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    },
    {
      id: 11,
      collection: "Prestias",
      productName: "Prestias-2",
      isWished: false,
      price: 143.95,
      totalPrice: 0,
      stone: "real diamond",
      carat: 1,
      cut: "heart",
      img: "./../../assets/images/collections/prestias/Prestias-2.jpg",
      material: "rose gold 18k",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    },
    {
      id: 12,
      collection: "Prestias",
      productName: "Prestias-3",
      isWished: false,
      price: 18.95,
      totalPrice: 0,
      stone: "cr ruby",
      carat: 2,
      cut: "heart",
      img: "./../../assets/images/collections/prestias/Prestias-3.jpg",
      material: "dipped rose gold",
      description: "blah blah blah",
      amount: 0,
      sale: 0.85,
      show: 0.8,
      sizes: 0,
      gallImages: 0
    }
  ];